spring:
  application:
    name: attendees
  profiles:
    active: dev 
  datasource:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: update  # or 'create' to force recreate the schema each time

ribbon:
  eureka:
    enabled: false

# don't do this in production, we are doing it here so that
# we can do features of Cloud Foundry without having to explain
# spring security
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
