allow_k8s_contexts('tap-gke-iterate')
allow_k8s_contexts('tap-iterate')
SOURCE_IMAGE = os.getenv("SOURCE_IMAGE", default='your-registry.io/project/polls-backend-source')
LOCAL_PATH = os.getenv("LOCAL_PATH", default='.')
NAMESPACE = os.getenv("NAMESPACE", default='demos')

k8s_custom_deploy(
    'polls-backend',
    apply_cmd="tanzu apps workload apply -f config/workload.yaml --live-update" +
               " --local-path " + LOCAL_PATH +
               " --source-image " + SOURCE_IMAGE +
               " --namespace " + NAMESPACE +
               " --yes >/dev/null" +
               " && kubectl get workload polls-backend --namespace " + NAMESPACE + " -o yaml",
    delete_cmd="tanzu apps workload delete -f config/workload.yaml --namespace " + NAMESPACE + " --yes",
    deps=['pom.xml', './target/classes'],
    container_selector='workload',
    live_update=[
      sync('./target/classes', '/workspace/BOOT-INF/classes')
    ]
)

k8s_resource('polls-backend', port_forwards=["8080:8080"],
            extra_pod_selectors=[{'serving.knative.dev/service': 'polls-backend'}])
